config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 post '/posts/new', to: 'posts#create'

 get 'setting', to: 'posts#setting'
 get 'myposts', to: 'posts#myposts'
 get 'mycomments', to: 'posts#mycomments'
 get 'commentstome', to: 'posts#commentstome'
 get 'postsselected', to: 'posts#postsselected'
  post '/comments/:id', to: 'comments#create'
  put '/comments/:id', to: 'comments#create'
  get 'edit_pass', to: 'users#edit_pass'
  patch 'update_pass', to: 'users#update_pass'
  patch 'update_veri', to: 'users#update_veri'
  get 'verification', to: 'users#verification'
  resources :posts
  resources :users do
      resources :posts,:comments
  end
   resources :posts do
      resources :comments
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord

  default_scope { order('created_at DESC') }
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   



  def show
    @post=Post.find(params[:post_id])
    
    @comments=@post.comments.all
    @comment=@post.comments.new
      session[:posts] ||= []
      session[:posts] << params[:post_id] 
      puts session[:posts].size
  end



  def new

    @post = Post.find(params[:post_id])
    @comment=@post.comments.new
    
  end

  def create
    @post = Post.find(params[:post_id]) 
    @comment=@post.comments.new(comment_params)
    @comment.user_id = current_user.id if current_user
    if @comment.save
      # successful save
      
      flash[:success] = "comment successful!"
      
      render 'show'
    else
      render 'show'
    end
  end

  def edit
    @user = User.find(params[:id])
    @post = current_user.posts.find(params[:id])
    @comment=@post.comments.find(params[:id])
  end



  def destroy
    current_user.comments.find(params[:id]).destroy
    flash[:success] = "comment deleted"
    redirect_to 'show'
  end

 

  private
  def comment_params
    params.require(:comment).permit(:comments)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Confirms an admin user.
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end


end

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.new]) do |f| %>


  <p>
  <%= f.label :Comments %><br>
  <%= f.text_area :comments %><br>
  </p>
  <%= f.submit yield(:button_text),class: "btn btn-primary" %>
  <% end %>

app/views/comments/new.html.erb
<% provide(:title, 'new comment') %>




<div class="row">
  <h1><%= @post.title %></h1>

  <div class= "text">

  <%= @post.content %>

  </div>
    <%= link_to "New Comment", new_post_comment_path, class: "btn btn-lg btn-primary" %>
    <div class = "row">
    <div>
    <h3> --- Comments:--</h3>
    </div>
    <% @post.comments.each do |comment| %>
    <li>
    <%= comment.comments %>
    <br>
    <%= link_to comment.user.email, comment.user %>
    </li>
    <% end %>
    

    </div>


  </div>

app/views/comments/show.html.erb
<% provide(:title, 'post and comments') %>
<% provide(:button_text, 'Post comments') %>


<div class="row">
  <h1><%= @post.title %></h1>

  <div class= "text">

  <%= @post.content %>

  </div>
    <%= render 'form' %>
    <div >
    ----Number of comments:
    <%= @post.comments.count %>
    </div>
    <div class = "row">
    <div>
    <h3> --- Comments:--</h3>
    </div>
   
   
    <% @post.comments.each do |comment| %>
    <li>
    <% if comment!=nil %>
    <%= gravatar_for comment.post.user %>
    <%= comment.comments %><br>
    <br>
    ----Commented by user:
    <%= comment.post.user.username %>
    <p><%= comment.created_at %></p>
    <br>
    ---------------------------------------------------------------------------------
    <br>
    <br>
    </li>
    <% end %>
    <% end %>
    
    </div>

</div>