config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 post '/posts/new', to: 'posts#create'

 get 'setting', to: 'posts#setting'
 get 'myposts', to: 'posts#myposts'
 get 'mycomments', to: 'posts#mycomments'
 get 'commentstome', to: 'posts#commentstome'
 get 'postsselected', to: 'posts#postsselected'
  post '/comments/:id', to: 'comments#create'
  put '/comments/:id', to: 'comments#create'
  get 'edit_pass', to: 'users#edit_pass'
  patch 'update_pass', to: 'users#update_pass'
  patch 'update_veri', to: 'users#update_veri'
  get 'verification', to: 'users#verification'
  resources :posts
  resources :users do
      resources :posts,:comments
  end
   resources :posts do
      resources :comments
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
   
    default_scope { order('updated_at DESC') }
    belongs_to :user
    has_many :comments
    validates :topic, presence: true, length: { maximum: 30}
    validates :title, presence: true, length: { maximum: 30}
    validates :content, presence: true, length: { maximum: 5000}
   


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def index
  @users = User.all.order("updated_at DESC")
  @posts = Post.all.order("updated_at DESC")
end

def show
  @post=Post.find(params[:id])
  
  
end

def new
  @post=current_user.posts.new
end

def setting
  @user = User.all
  @posts = Post.all
end
def create
  @post=current_user.posts.new(post_params)
  if @post.topic==''
    @post.topic="New"
  end
  if @post.save
  flash[:success] = "post successful"
  redirect_to posts_path
  else
    render 'new'
  end

end
def myposts
end
def commentstome
end
def postsselected
   @users = User.all.order("updated_at DESC")
   @array=session[:posts]
   @posts=Post.find(session[:posts])
end
def destroy
  Post.find(params[:id]).destroy
  flash[:success]= "post deleted"
  redirect_to posts_path
end

private

  def post_params
    params.require(:post).permit(:topic, :title, :content, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h1>New Post</h1>
<%= form_for(@post, url: new_post_path) do |f| %>
<p>
  <%= f.label :topic %><br>
   <%= f.select :topic, ['AI', 'Topic2', 'Topic3', 'Topic4' ], { :include_blank => '-- Select One --' } %>

     <%#= f.text_field :topic %><br>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  </p>

  <p>
  <%= f.label :content %><br>
  <%= f.text_area :content %><br>
  </p>
  <%= f.submit %>
<% end %>

app/views/posts/_navbar.html.erb
<% if logged_in? %>

  <div class="bar">

  <nav>
      <ul class="nav navbar-nav ">
        <li><%= link_to "Recent Post",   posts_path %></li>
        <li><%= link_to "Selected Post",   postsselected_path %></li>
        <li><%= link_to "My Setting",  "setting" %></li>
        
      </ul>
    </nav>

   <%= form_tag("#", :method => "get",
    class: 'navbar-form navbar-left') do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
      </div>
    </div>
    <% end %>

     <%= link_to "New Post", new_post_path, class: "btn btn-lg btn-primary" %>
</div>




<% end %>

app/views/posts/_sidebar.html.erb
<% if logged_in? %>
<div class="col-md-1 col-md-1 col-md-1 col-md-1 "position-relative" ">
  <ul class="nav nav-siderbar nav-left">
    <li class="sidebar_profile"><%= link_to  "My Profile", current_user %>
    </li>
    <li>
      <%= link_to  "My Posts", myposts_path %>
    </li>
    <li>
      <%= link_to  "My Comments", mycomments_path %>
    </li>
    <li>
      <%= link_to  "Comments to Me", commentstome_path %>
    </li>
    <li>
      <%= link_to  "Setting", setting_path %>
    </li>
  </ul>
</div>
<% end %>

    

app/views/posts/commentstome.html.erb
<% provide(:title, ' comments to me') %>

<div class="row">
 
    <%= render 'sidebar' %>

    <div>
<div class = "show comments">
 <% current_user.posts.each do |post| %>
    
  <% post.comments.each do |comment| %>


    <li>
    <%= gravatar_for comment.user %>
    <%= link_to comment.comments, post_comment_path(comment.post,comment.post.id) %><br>
    <br>
    ----Commented by user:
    <%=  comment.user.email %>
    <br>
    ---------------------------------------------------------------------------------
    <br>
    <br>
    </li>
    <% end %>
    <% end %>
    </div>

app/views/posts/index.html.erb
<% provide(:title, 'forum') %>




<div class="row">
  
    <%= render 'navbar' %>
 </div>

<div class="position-relative d-inline " >
debug All post here:

<div class= "row " >
 
 <% @users.each do |user| %>
    <% user.posts.each do |post| %>
    <div class="show users col-sm d-inline" >
    
      <%= gravatar_for user, size: 60 %>
    
     <li>
      user name: 
      <%= link_to user.username, user %>
      <br>
      
      <%= link_to post.updated_at, "#" %>
      <br>
      <div class="btn">
      title:

      <%= link_to post.title, post_comment_path(post,post.id) %>
      </div>
      </li>
     </div>
     <% end %>
    
   
  <% end %>
  </div>




</div>
<br>
<div class= "row" >
All users
 <% @users.each do |user| %>
    
    <div class="show users col-sm d-inline" >
    <li>
      <%= gravatar_for user, size: 25 %>
    
    
      username: 
      <%= link_to user.username, user %>
     </li>
     </div>
   
  <% end %>
  </div>


  <div class= "row " >
  topic:
 
    <% temps=@posts.to_set %>
    <% temps.each do |post| %>
    <div class="show users col-sm d-inline" >
    
     
    
     <li>
   
      
      <%= link_to post.topic, "#" %>
      </li>
     </div>
     <% end %>
    
   
  
  </div>

app/views/posts/mycomments.html.erb
<% provide(:title, 'My posts') %>

<div class="row">
 
    <%= render 'sidebar' %>

    <div>
    My comments:

     
    <% current_user.comments.each do |comment| %>
    <li>
    <%= comment.created_at %><br>
    <%= link_to comment.comments , post_comment_path(comment.post,comment.post.id) %><br>
    
   
    </li>
    <% end %>

    </div>

</div>

app/views/posts/myposts.html.erb
<% provide(:title, 'My posts') %>

<div class="row">
 
    <%= render 'sidebar' %>


    My post:

       
    <% current_user.posts.each do |post| %>
    <li>
   
    <%= link_to post.title, post_comment_path(post,post.id) %><br>
   
    <% end %>



</div>

app/views/posts/new.html.erb
<% provide(:title, 'post') %>
<% provide(:button_text, 'Create a new post') %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <button type="button" class="btn btn-warning">
    <%= link_to "cancel", posts_path %>
    
    </button>
    
  </div>
</div>

app/views/posts/postsselected.html.erb
<% provide(:title, 'post selected') %>



<div class="row">
  
    <%= render 'navbar' %>
 </div>
 <% @array.each do |t| %>
<%= puts t %>
<% end %>

 <div class= "row " >
 
 
    <% @posts.each do |post| %>
    <div class="show users col-sm d-inline" >
    
      <%= gravatar_for post.user, size: 60 %>
    
     <li>
      user name: 
      <%= link_to post.user.username, post.user %>
      <br>
      
      <%= link_to post.updated_at, "#" %>
      <br>
      <div class="btn">
      title:

      <%= link_to post.title, post_comment_path(post,post.id) %>
      </div>
      </li>
     </div>
     <% end %>
    
   
 
  </div>







<div class= "row" >
All users
 <% @users.each do |user| %>
    
    <div class="show users col-sm d-inline" >
    <li>
      <%= gravatar_for user, size: 25 %>
    
    
      username: 
      <%= link_to user.username, user %>
     </li>
     </div>
   
  <% end %>
  </div>


  <div class= "row " >
  topic:
 
    <% temps=@posts.to_set %>
    <% temps.each do |post| %>
    <div class="show users col-sm d-inline" >
    
     
    
     <li>
   
      
      <%= link_to post.topic, "#" %>
      </li>
     </div>
     <% end %>
    
   
  
  </div>

app/views/posts/setting.html.erb
<% provide(:title, 'My setting') %>




<div class="row">
 
    <%= render 'sidebar' %>

</div>

 <nav class= "bar">
      <ul class="nav navbar-nav ">
        <li><%= link_to "Personal Info",   edit_user_path(current_user) %></li>
        <li><%= link_to "Avatar " ,   "#" %></li>
        <li><%= link_to "Password",  edit_pass_path %></li>
        <li><%= link_to "Verification",  verification_path %></li>
      </ul>
    </nav>