config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

 post '/posts/new', to: 'posts#create'

 get 'setting', to: 'posts#setting'
 get 'myposts', to: 'posts#myposts'
 get 'mycomments', to: 'posts#mycomments'
 get 'commentstome', to: 'posts#commentstome'
 get 'postsselected', to: 'posts#postsselected'
  post '/comments/:id', to: 'comments#create'
  put '/comments/:id', to: 'comments#create'
  get 'edit_pass', to: 'users#edit_pass'
  patch 'update_pass', to: 'users#update_pass'
  patch 'update_veri', to: 'users#update_veri'
  get 'verification', to: 'users#verification'
  resources :posts
  resources :users do
      resources :posts,:comments
  end
   resources :posts do
      resources :comments
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
   
  </small>
  <nav>
    <ul>
      <li><%= link_to "s3620189",   "#" %></li>
      
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <% if logged_in? %>
    <%= link_to "News", posts_path, id: "logo" %>


    
    <% else %>
   
    <%= link_to "assignment app", posts_path, id: "logo" %>
   <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   posts_path %></li>
        <li><%= link_to "News",   help_path %></li>
        <% if logged_in? %>
          
          <li> <%= link_to current_user.username, users_path %></li>
         
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li><%= gravatar_for current_user,size: 50 %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>

  <div class="bar">

  <nav>
      <ul class="nav navbar-nav ">
        <li><%= link_to "Recent Post",   "#" %></li>
        <li><%= link_to "Selected Post",   "#" %></li>
        <li><%= link_to "My Setting",  "#" %></li>
        
      </ul>
    </nav>

   <%= form_tag("#", :method => "get",
    class: 'navbar-form navbar-left') do %>
    <div class="input-group">
      <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
      <div class="input-group-btn">
        <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>
      </div>
    </div>
    <% end %>

     <%= link_to "New Post", "#", class: "btn btn-lg btn-primary" %>
</div>




<% end %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<% if logged_in? %>
<div class="col-md-1 col-md-1 col-md-1 col-md-1 ">
  <ul class="nav nav-siderbar nav-left">
    <li class="sidebar_profile"><%= link_to  "My Profile", current_user %>
    </li>
    <li>
      <%= link_to  "My Posts", "#" %>
    </li>
    <li>
      <%= link_to  "My Comments", "#" %>
    </li>
    <li>
      <%= link_to  "Comments to Me", "#" %>
    </li>
    <li>
      <%= link_to  "Setting", edit_user_path(current_user) %>
    </li>
  </ul>
</div>
<% end %>

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>


      
    <div class="container-fluid">
    
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
     
          <%= yield %>
     
       
        <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>

    </div>

       

  </body>
</html>